apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kodo-agent
  labels:
    {{- include "kodo-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kodo-agent
subjects:
- kind: ServiceAccount
  name: kodo-agent
  namespace: {{ include "kodo-agent.namespace" . }}
