apiVersion: v1
kind: ConfigMap
metadata:
  name: kodo-config
  namespace: {{ include "kodo-agent.namespace" . }}
  labels:
    {{- include "kodo-agent.labels" . | nindent 4 }}
data:
  API_ENDPOINT: {{ .Values.agent.apiEndpoint | quote }}
  COLLECT_INTERVAL: {{ .Values.agent.collectInterval | quote }}
  LOG_LEVEL: {{ .Values.agent.logLevel | quote }}
