apiVersion: v1
kind: Secret
metadata:
  name: kodo-secret
  namespace: {{ include "kodo-agent.namespace" . }}
  labels:
    {{- include "kodo-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ required "agent.apiKey is required" .Values.agent.apiKey | quote }}
  CLUSTER_ID: {{ required "agent.clusterId is required" .Values.agent.clusterId | quote }}
