-- Migration: Create Storage Recommendations table for AI-powered rightsizing suggestions
-- This stores recommendations generated by AI analysis of PVC usage patterns

-- Create table for storage recommendations
CREATE TABLE public.storage_recommendations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    pvc_name TEXT NOT NULL,
    namespace TEXT NOT NULL,
    cluster_id UUID NOT NULL REFERENCES public.clusters(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

    -- Current metrics
    current_size_gb NUMERIC(10,2) NOT NULL,
    recommended_size_gb NUMERIC(10,2) NOT NULL,
    current_usage_gb NUMERIC(10,2) NOT NULL,

    -- Usage statistics from analysis
    avg_usage_percent NUMERIC(5,2) NOT NULL,
    max_usage_percent NUMERIC(5,2) NOT NULL,
    p95_usage_percent NUMERIC(5,2) NOT NULL,

    -- Recommendation type and status
    recommendation_type TEXT NOT NULL CHECK (recommendation_type IN ('downsize', 'upsize', 'maintain', 'delete')),
    priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'applied')),

    -- Cost savings
    potential_savings_month NUMERIC(10,2) DEFAULT 0,

    -- AI analysis details
    ai_reasoning TEXT NOT NULL,
    ai_confidence NUMERIC(3,2) DEFAULT 0.85,
    days_analyzed INTEGER DEFAULT 7,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    applied_at TIMESTAMPTZ,

    -- Only one pending recommendation per PVC
    UNIQUE(cluster_id, pvc_name, namespace, status)
);

-- Index for filtering by cluster
CREATE INDEX idx_storage_recommendations_cluster ON public.storage_recommendations(cluster_id);

-- Index for filtering by status
CREATE INDEX idx_storage_recommendations_status ON public.storage_recommendations(status);

-- Index for filtering by user
CREATE INDEX idx_storage_recommendations_user ON public.storage_recommendations(user_id);

-- Index for priority sorting
CREATE INDEX idx_storage_recommendations_priority ON public.storage_recommendations(priority DESC, potential_savings_month DESC);

-- Enable Row Level Security
ALTER TABLE public.storage_recommendations ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view their own recommendations
CREATE POLICY "Users can view own storage_recommendations"
ON public.storage_recommendations FOR SELECT TO authenticated
USING (user_id = auth.uid());

-- Policy: Users can update their own recommendations (accept/reject)
CREATE POLICY "Users can update own storage_recommendations"
ON public.storage_recommendations FOR UPDATE TO authenticated
USING (user_id = auth.uid());

-- Policy: Users can delete their own recommendations
CREATE POLICY "Users can delete own storage_recommendations"
ON public.storage_recommendations FOR DELETE TO authenticated
USING (user_id = auth.uid());

-- Policy: Service role can insert recommendations
CREATE POLICY "Service role can insert storage_recommendations"
ON public.storage_recommendations FOR INSERT TO service_role
WITH CHECK (true);

-- Policy: Service role can manage all recommendations
CREATE POLICY "Service role can manage storage_recommendations"
ON public.storage_recommendations FOR ALL TO service_role
USING (true);

-- Enable real-time for storage_recommendations
ALTER TABLE public.storage_recommendations REPLICA IDENTITY FULL;
ALTER PUBLICATION supabase_realtime ADD TABLE public.storage_recommendations;
